import numpy as np

ADDRESSES = ('AN GIANG',
    'BÌNH DƯƠNG',
    'BÌNH PHƯỚC',
    'BÌNH THUẬN',
    'BÌNH ĐỊNH',
    'BẠC LIÊU',
    'BẮC GIANG',
    'BẮC NINH',
    'BẾN TRE',
    'CAO BẰNG',
    'CÀ MAU',
    'CẦN THƠ',
    'GIA LAI',
    'HÀ GIANG',
    'HÀ NAM',
    'HÀ NỘI',
    'HÀ TĨNH',
    'HÒA BÌNH',
    'HƯNG YÊN',
    'HẢI DƯƠNG',
    'HẢI PHÒNG',
    'HẬU GIANG',
    'HỒ CHÍ MINH',
    'KHÁNH HÒA',
    'KIÊN GIANG',
    'KON TUM',
    'LAI CHÂU',
    'LONG AN',
    'LÀO CAI',
    'LÂM ĐỒNG',
    'NAM ĐỊNH',
    'NGHỆ AN',
    'NINH BÌNH',
    'NINH THUẬN',
    'PHÚ THỌ',
    'PHÚ YÊN',
    'QUẢNG BÌNH',
    'QUẢNG NAM',
    'QUẢNG NGÃI',
    'QUẢNG NINH',
    'QUẢNG TRỊ',
    'SÓC TRĂNG',
    'SƠN LA',
    'THANH HÓA',
    'THÁI BÌNH',
    'THÁI NGUYÊN',
    'TIỀN GIANG',
    'TRÀ VINH',
    'TUYÊN QUANG',
    'TÂY NINH',
    'VĨNH LONG',
    'VĨNH PHÚC',
    'VŨNG TÀU',
    'YÊN BÁI',
    'ĐIỆN BIÊN',
    'ĐÀ NẴNG',
    'ĐỒNG NAI',
    'ĐỒNG THÁP')
ADDRESSES = tuple(map(str.lower, ADDRESSES))
SKILLS = ('An ninh',
    'Bán hàng',
    'Bán lẻ',
    'Bán sỉ',
    'Bảo vệ',
    'Chăm sóc sức khỏe',
    'Chứng khoán',
    'Cơ khí',
    'Dầu khí',
    'Dịch vụ khách hàng',
    'Giao nhận',
    'Giải trí',
    'Hành chính',
    'Hóa học',
    'In ấn',
    'Kho vận',
    'Kinh doanh',
    'Kiểm toán',
    'Kế toán',
    'Lao động phổ thông',
    'Luật',
    'Marketing',
    'Mỹ thuật',
    'Nghệ thuật',
    'Ngân hàng',
    'Nhân sự',
    'Nhập khẩu',
    'Pháp lý',
    'Phần cứng',
    'Phần mềm',
    'Quản lý',
    'Quản lý chất lượng',
    'Quảng cáo',
    'Sản xuất',
    'Thiết kế',
    'Thu mua',
    'Thư ký',
    'Thống kê',
    'Thực phẩm',
    'Tiếp thị',
    'Truyền thông',
    'Tài chính',
    'Tự động hóa',
    'Vận chuyển',
    'Vận hành sản xuất',
    'Vật tư',
    'Xuất bản',
    'Y tế',
    'Ô tô',
    'Điều hành',
    'Điện',
    'Điện lạnh',
    'Điện tử',
    'Đầu tư',
    'Đối ngoại',
    'Đồ uống')
SKILLS = tuple(map(str.lower, SKILLS))
LEVELS = ('Giám đốc', 'Mới tốt nghiệp', 'Nhân viên', 'Quản lý', 'Trưởng nhóm')
LEVELS = tuple(map(str.lower, LEVELS))

JOB_PROPERTY_TO_ID = {}
PROPERTY_COUNT = 0
for skill in SKILLS:
    JOB_PROPERTY_TO_ID[skill] = PROPERTY_COUNT
    PROPERTY_COUNT += 1
for level in LEVELS:
    JOB_PROPERTY_TO_ID[level] = PROPERTY_COUNT
    PROPERTY_COUNT += 1
PROPERTY_COUNT += 1 # for salary property
MAX_SALARY = 20000000
# PROPERTY_WEIGHTS = np.array([1.0/PROPERTY_COUNT for i in range(PROPERTY_COUNT)])
salary_weight = 0.01
PROPERTY_WEIGHTS = np.array([(1.0 - salary_weight)/(PROPERTY_COUNT - 1) for i in range(PROPERTY_COUNT)])
PROPERTY_WEIGHTS[-1] = salary_weight
